# -*- coding: utf-8 -*-
"""Medical App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kt5Ql7X3BMXjRcvuQOsVD-bUsQsvIjug
"""

import streamlit as st
import pandas as pd
import altair as alt
from supabase import create_client, Client
import datetime

# ==============================================================================
# CONFIGURACIÓN E INICIALIZACIÓN
# ==============================================================================
st.set_page_config(
    page_title="Portal Médico - Gestión de Liquidaciones",
    page_icon="👨‍⚕️",
    layout="wide"
)

# Estilos CSS para limpiar la interfaz y dar toque médico/profesional
st.markdown("""
<style>
    .metric-card {
        background-color: #f0f2f6;
        padding: 15px;
        border-radius: 10px;
        border-left: 5px solid #2E86C1;
    }
    div[data-testid="stMetricValue"] {
        font-size: 1.8rem;
    }
</style>
""", unsafe_allow_html=True)

# Inicializar conexión a Supabase usando Secrets de Streamlit Cloud
# Esto es vital: No hardcodeamos claves aquí.
@st.cache_resource
def init_connection():
    try:
        url = st.secrets["SUPABASE_URL"]
        key = st.secrets["SUPABASE_KEY"]
        return create_client(url, key)
    except Exception as e:
        st.error("⚠️ Error de configuración: No se encontraron los secretos de Supabase.")
        st.stop()

supabase = init_connection()

# ==============================================================================
# FUNCIONES DE CARGA DE DATOS (CON CACHE)
# ==============================================================================
@st.cache_data(ttl=600) # Recargar datos cada 10 minutos automáticamente
def get_financial_summary():
    # Traemos transacciones para métricas
    # Nota: Si la tabla crece mucho, cambiar a query agregada en RPC de Supabase
    response = supabase.table("transactions").select("*").execute()
    df = pd.DataFrame(response.data)

    if df.empty:
        return df

    # Normalización de datos
    df['payment_date'] = pd.to_datetime(df['payment_date'])
    df['event_date'] = pd.to_datetime(df['event_date'])
    df['net_amount'] = pd.to_numeric(df['net_amount'])

    # Columnas derivadas para gráficos
    df['Mes_Pago'] = df['payment_date'].dt.strftime('%Y-%m')
    df['Año'] = df['payment_date'].dt.year

    return df

def search_patient_history(search_term):
    # Búsqueda insensible a mayúsculas (ILIKE) en nombre normalizado
    response = supabase.table("patients")\
        .select("id, full_name, aliases")\
        .ilike("normalized_name", f"%{search_term.lower()}%")\
        .execute()

    patients = response.data
    return patients if patients else []

def get_transactions_by_patient(patient_id):
    response = supabase.table("transactions")\
        .select("*")\
        .eq("patient_id", patient_id)\
        .order("event_date", desc=True)\
        .execute()

    df = pd.DataFrame(response.data)
    if not df.empty:
        # Convertir a datetime para visualización
        df['event_date'] = pd.to_datetime(df['event_date']).dt.date
        df['payment_date'] = pd.to_datetime(df['payment_date']).dt.date
    return df

# ==============================================================================
# INTERFAZ PRINCIPAL
# ==============================================================================

st.title("👨‍⚕️ Portal de Gestión Financiera")
st.markdown("Visión unificada de liquidaciones **AMCA** y **Clínica Alemana**.")
st.markdown("---")

# Carga inicial
with st.spinner('Conectando con base de datos segura...'):
    df_main = get_financial_summary()

if df_main.empty:
    st.info("👋 Bienvenido. Aún no hay liquidaciones procesadas en el sistema. Los datos aparecerán aquí automáticamente cuando n8n procese los correos.")
    st.stop()

# --- SIDEBAR: FILTROS GLOBALES ---
with st.sidebar:
    st.header("🔍 Filtros de Visualización")

    # Filtro de Año Dinámico
    years = sorted(df_main['Año'].unique(), reverse=True)
    selected_year = st.selectbox("Año Fiscal", years)

    # Aplicar filtro
    df_filtered = df_main[df_main['Año'] == selected_year]

    st.markdown("---")
    st.caption("Sistema automatizado v1.0")
    st.caption("Desarrollado con n8n + Supabase")

# --- ESTRUCTURA DE PESTAÑAS ---
tab1, tab2, tab3 = st.tabs(["📊 Tablero Financiero", "🔎 Historial Paciente", "📑 Detalle de Pagos"])

# ------------------------------------------------------------------------------
# TAB 1: DASHBOARD
# ------------------------------------------------------------------------------
with tab1:
    # 1. KPIs Principales
    total_anual = df_filtered['net_amount'].sum()

    # Calcular promedio solo con meses que tienen datos para no diluir el promedio
    meses_con_datos = df_filtered['Mes_Pago'].nunique()
    promedio_mes = total_anual / meses_con_datos if meses_con_datos > 0 else 0

    count_cirugias = len(df_filtered)

    # Layout de Métricas
    c1, c2, c3 = st.columns(3)
    c1.metric("Ingreso Líquido (Año Seleccionado)", f"${total_anual:,.0f}".replace(",", "."))
    c2.metric("Promedio Mensual Real", f"${promedio_mes:,.0f}".replace(",", "."))
    c3.metric("Prestaciones Liquidadas", count_cirugias)

    st.markdown("---")

    # 2. Gráficos
    col_g1, col_g2 = st.columns([2, 1])

    with col_g1:
        st.subheader("Evolución de Pagos Mensuales")
        # Agrupación por Mes y Fuente
        chart_data = df_filtered.groupby(['Mes_Pago', 'source'])['net_amount'].sum().reset_index()

        bar_chart = alt.Chart(chart_data).mark_bar().encode(
            x=alt.X('Mes_Pago', title='Mes'),
            y=alt.Y('net_amount', title='Monto ($)'),
            color=alt.Color('source', title='Origen', scale=alt.Scale(scheme='tableau10')),
            tooltip=['Mes_Pago', 'source', alt.Tooltip('net_amount', format=',.0f')]
        ).interactive()

        st.altair_chart(bar_chart, use_container_width=True)

    with col_g2:
        st.subheader("Origen de Ingresos")
        pie_data = df_filtered.groupby('source')['net_amount'].sum().reset_index()

        pie_chart = alt.Chart(pie_data).mark_arc(innerRadius=60).encode(
            theta=alt.Theta(field="net_amount", type="quantitative"),
            color=alt.Color(field="source", type="nominal"),
            tooltip=['source', alt.Tooltip('net_amount', format=',.0f')]
        )
        st.altair_chart(pie_chart, use_container_width=True)

# ------------------------------------------------------------------------------
# TAB 2: BUSCADOR PACIENTES
# ------------------------------------------------------------------------------
with tab2:
    st.markdown("Busque un paciente para ver **todas** sus liquidaciones históricas (ambulatorias y hospitalarias).")

    col_search, col_btn = st.columns([3, 1])
    query = col_search.text_input("Nombre o Apellido", placeholder="Ej: HAEUSSLER")

    if query:
        results = search_patient_history(query)

        if not results:
            st.warning("No se encontraron coincidencias.")
        else:
            # Dropdown para elegir paciente específico
            patient_map = {p['id']: f"{p['full_name']}" for p in results}
            selected_id = st.selectbox("Seleccione Paciente:", options=patient_map.keys(), format_func=lambda x: patient_map[x])

            st.divider()

            # Detalle del Paciente
            history = get_transactions_by_patient(selected_id)

            if not history.empty:
                total_paciente = history['net_amount'].sum()
                st.success(f"Total histórico liquidado por este paciente: **${total_paciente:,.0f}".replace(",", ".") + "**")

                st.dataframe(
                    history[['event_date', 'description', 'source', 'net_amount', 'payment_date']],
                    column_config={
                        "event_date": "Fecha Atención",
                        "description": "Prestación",
                        "source": "Institución",
                        "net_amount": st.column_config.NumberColumn("Monto", format="$%d"),
                        "payment_date": "Fecha Pago"
                    },
                    use_container_width=True,
                    hide_index=True
                )
            else:
                st.info("Paciente registrado pero sin transacciones activas.")

# ------------------------------------------------------------------------------
# TAB 3: DATA RAW
# ------------------------------------------------------------------------------
with tab3:
    st.markdown("Listado completo de liquidaciones para auditoría.")

    # Buscador en tiempo real sobre la tabla
    text_search = st.text_input("Filtrar tabla por glosa o detalle:", "")

    df_display = df_filtered.copy()
    if text_search:
        df_display = df_display[df_display['description'].astype(str).str.contains(text_search, case=False, na=False)]

    st.dataframe(
        df_display[['payment_date', 'raw_patient_name', 'description', 'source', 'net_amount']],
        column_config={
            "payment_date": st.column_config.DateColumn("Fecha Pago", format="DD/MM/YYYY"),
            "raw_patient_name": "Paciente (Reporte)",
            "description": "Glosa",
            "source": "Origen",
            "net_amount": st.column_config.NumberColumn("Monto Líquido", format="$%d")
        },
        use_container_width=True,
        height=600
    )